# Generated by Django 3.0.4 on 2020-04-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('I', 'Installed'), ('P', 'Installing'), ('F', 'Failed'), ('U', 'Not installed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('hash', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('R', 'Running'), ('C', 'Completed')], max_length=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App')),
            ],
        ),
    ]
